name: HexWorld hexcom

on:
  push:
    branches:
      - main
    paths:
      - 'src/hexcom/**'
      - 'api/hexagon.proto'
  pull_request:
    branches:
      - main
    paths:
      - 'src/hexcom/**'
      - 'api/hexagon.proto'
  workflow_dispatch:

jobs:
  build-hexcom:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v3
      - name: powershell allow...
        shell: cmd
        run: powershell -Command "Set-ExecutionPolicy RemoteSigned -Scope CurrentUser"
      - name: Configure 
        working-directory: ./src/hexcom
        run:  |
          Import-Module "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
          Enter-VsDevShell d5b09b2d
          git submodule update --init --recursive
          ./vcpkg/bootstrap-vcpkg.bat
          ./vcpkg/vcpkg.exe install cli --triplet x64-windows
          mkdir build
          & "C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_TOOLCHAIN_FILE=".\vcpkg\scripts\buildsystems\vcpkg.cmake" -G Ninja -S . -B build 
      - name: Build
        working-directory: ./src/hexcom
        run:  |
          Import-Module "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
          Enter-VsDevShell d5b09b2d
          & "C:\Program Files\CMake\bin\cmake.exe" --build build --target hexworld_client -j12 
      - name: Create zip
        working-directory: ./src/hexcom
        run:  |
          & "C:\Program Files\CMake\bin\cmake.exe" --build build --target create_zip -j12 
       
          
