name: HexWorld hexcom

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-hexcom:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v2
      - name: Build and zip
        working-directory: ./src/hexcom
        run: C:\Users\cyber\AppData\Local\JetBrains\Toolbox\apps\CLion\ch-0\221.5921.27\bin\cmake\win\bin\cmake.exe --build cmake-build-debug --target create_zip -j 12
