name: HexWorld

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-hexcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Generate gRPC and Protocol buffer files
        working-directory: ./src/hexcloud
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go
          install google.golang.org/grpc/cmd/protoc-gen-go-grpc
          protoc --go_out=./internal/pkg  --go-grpc_out=./internal/pkg ./api/hexagon.proto
      - name: Build hexcloud
        working-directory: ./src/hexcloud
        run: go build -v ./...

      - name: Test hexcloud
        working-directory: ./src/hexcloud
          run: go test -v ./...
