name: HexWorld hexcom

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-hexcom:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v2
      - name: Build and zip
        working-directory: ./src/hexcom
        run:  |
          git submodule update --init --recursive
          ./vcpkg/bootstrap-vcpkg.bat
          ./vcpkg/vcpkg.exe install cli
          mkdir build
          & "C:\Program Files\CMake\bin\cmake.exe" -GNinja -DCMAKE_TOOLCHAIN_FILE=C:/actions-runner/_work/hexrepo/hexrepo/src/hexcom/vcpkg/scripts/buildsystems/vcpkg.cmake .
          & "C:\Program Files\CMake\bin\cmake.exe" --build . --target create_zip -j12 -- -DCMAKE_TOOLCHAIN_FILE=C:/actions-runner/_work/hexrepo/hexrepo/src/hexcom/vcpkg/scripts/buildsystems/vcpkg.cmake
