name: HexWorld hexcom

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-hexcom:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v2
      - name: Build and zip
        working-directory: ./src/hexcom
        run:  |
          mkdir build
          & "C:\Program Files\CMake\bin\cmake.exe" --configure .
          & "C:\Program Files\CMake\bin\cmake.exe" --build build --target create_zip 
