name: HexWorld hexcom

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-hexcom:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v2
      - name: Build and zip
        working-directory: ./src/hexcom
        run:  |
          Import-Module "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
          Enter-VsDevShell d5b09b2d
          git submodule update --init --recursive
          ./vcpkg/bootstrap-vcpkg.bat
          ./vcpkg/vcpkg.exe install cli --triplet x64-windows
          mkdir build
          & "C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_TOOLCHAIN_FILE=".\vcpkg\scripts\buildsystems\vcpkg.cmake" -G Ninja -S . -B build 
          & "C:\Program Files\CMake\bin\cmake.exe" --build build --target hexworld_client -j12 
