name: HexWorld hexcli

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-hexcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Generate gRPC and Protocol buffer files
        working-directory: ./src/hexcli
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          sudo apt install protobuf-compiler
          protoc --go_out=./internal/pkg  --go-grpc_out=./internal/pkg ./api/hexagon.proto
      - name: Build hexcli
        working-directory: ./src/hexcli
        run: go build -v ./...

      - name: Test hexcli
        working-directory: ./src/hexcli
        run: go test -v ./...
