name: Build and Deploy to Cloud Run

on:
  workflow_run:
      workflows: ["HexWorld hexcloud"]
      branches: [main]
      types: 
        - completed

# Environment variables available to all jobs and steps in this workflow
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  RUN_REGION: us-east1
  SERVICE_NAME: hexcloud

jobs:
  job_id:
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    # Configure gcloud CLI
    - name: gcloud Set up
      working-directory: ./src/hexcloud
      run: |
        gcloud config set project $PROJECT_ID

    # Build and push image to Google Container Registry
    - name: Build
      working-directory: ./src/hexcloud
      run: |
        gcloud builds submit -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA --timeout 20m .
    # Deploy image to Cloud Run
    - name: Deploy
      working-directory: ./src/hexcloud
      run: |
        gcloud run deploy $SERVICE_NAME \
          --region $RUN_REGION \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
          --platform managed \
          --allow-unauthenticated
          