name: Build and Deploy to Cloud Run

on:
  workflow_run:
      workflows: ["HexWorld hexcloud"]
      branches: [main]
      types: 
        - completed

# Environment variables available to all jobs and steps in this workflow
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  RUN_REGION: us-east1
  SERVICE_NAME: hexcloud

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@main
        with:
          version: '275.0.0'
          service_account_email: ${{ secrets.SA_EMAIL }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}

      # Configure gcloud CLI
      - name: gcloud Set up
        working-directory: ./src/hexcloud
        run: |
          gcloud config set project $PROJECT_ID

      # Build and push image to Google Container Registry
      - name: Build
        working-directory: ./src/hexcloud
        run: |
          gcloud builds submit -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA --timeout 20m .
      # Deploy image to Cloud Run
      - name: Deploy
        working-directory: ./src/hexcloud
        run: |
          gcloud run deploy $SERVICE_NAME \
            --region $RUN_REGION \
            --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
            --platform managed \
            --allow-unauthenticated